Repository hmcts/darts-stub-services, pull requests merged in 2024-10, with the labels that each got.

#180 DMP-3844 - ARM RPO - Stub for new ARM endpoint - removeProduction
  wiremock/mappings/arm/v1_removeProduction.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-stub-services-pr-180

#191 DMP-3843: ARM RPO - Stub for new ARM endpoint - getExtendedSearchesByMatter
  wiremock/mappings/arm/v1_getExtendedSearchesByMatter.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-stub-services-pr-191

#190 DMP-3803: ARM RPO - Stub for new ARM endpoint - getProductionOutputFiles
  wiremock/mappings/arm/v1_getProductionOutputFiles.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-stub-services-pr-190

#185 DMP-3798: ARM RPO - Stub for new ARM endpoint - getMasterIndexFieldByRecordClassSchema
  wiremock/mappings/arm/v1_getMasterIndexFieldByRecordClassSchema.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-stub-services-pr-185

#186 DMP-3799: ARM RPO - Stub for new ARM endpoint - addAsyncSearch
  wiremock/mappings/arm/v1_addAsyncSearch.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-stub-services-pr-186

#187 DMP-3800: ARM RPO - Stub for new ARM endpoint - SaveBackgroundSearch
  wiremock/mappings/arm/v1_SaveBackgroundSearch.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-stub-services-pr-187

#188 DMP-3801: ARM RPO - Stub for new ARM endpoint - createExportBasedOnSearchResultsTable
  wiremock/mappings/arm/v1_createExportBasedOnSearchResultsTable.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-stub-services-pr-188

#189 DMP-3802: ARM RPO - Stub for new ARM endpoint - getExtendedProductionByMatter
  wiremock/mappings/arm/v1_getExtendedProductionsByMatter.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-stub-services-pr-189

#181 DMP-3527: ARM RPO - Stub for new ARM endpoint - getRecordManagementMatter
  wiremock/mappings/arm/v1_getRecordManagementMatter.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-stub-services-pr-181

#182 DMP-3795: ARM RPO - Stub for new ARM endpoint - getIndexesByMatterId
  wiremock/mappings/arm/v1_getIndexesByMatterId.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-stub-services-pr-182

#183 DMP-3796: ARM RPO - Stub for new ARM endpoint - getStorageAccounts
  wiremock/mappings/arm/v1_getStorageAccounts.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-stub-services-pr-183

#184 DMP-3797: ARM RPO - Stub for new ARM endpoint - getProfileEntitlements
  wiremock/mappings/arm/v1_getProfileEntitlements.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-stub-services-pr-184

#192 DMP-3804: ARM RPO - Stub for new ARM endpoint - downloadProduction
  wiremock/__files/downloadProduction/CSV.csv
  wiremock/mappings/arm/v1_downloadProduction.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-stub-services-pr-192

#196 DMP-4125: Correct getStorageAccounts response
  wiremock/mappings/arm/v1_getStorageAccounts.json
Labels: ns:darts-modernisation, prd:darts, rel:darts-stub-services-pr-196
